apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    url: postgres:5432
    database: hidroelectrica
    user: hidro
    secureJsonData:
      password: hidro1234
    jsonData:
      sslmode: disable
      defaultDatabase: hidroelectrica